-- https://www.firebirdnews.org/listing-the-foreign-keys-in-a-firebird-database/

SELECT rc.RDB$CONSTRAINT_NAME AS CONSTRAINT_NAME,
i.RDB$RELATION_NAME AS TABLE_NAME,
s.RDB$FIELD_NAME AS FIELD_NAME
FROM RDB$INDEX_SEGMENTS s
LEFT JOIN RDB$INDICES i ON i.RDB$INDEX_NAME = s.RDB$INDEX_NAME
LEFT JOIN RDB$RELATION_CONSTRAINTS rc ON rc.RDB$INDEX_NAME = s.RDB$INDEX_NAME
LEFT JOIN RDB$REF_CONSTRAINTS refc ON rc.RDB$CONSTRAINT_NAME = refc.RDB$CONSTRAINT_NAME
LEFT JOIN RDB$RELATION_CONSTRAINTS rc2 ON rc2.RDB$CONSTRAINT_NAME = refc.RDB$CONST_NAME_UQ
LEFT JOIN RDB$INDICES i2 ON i2.RDB$INDEX_NAME = rc2.RDB$INDEX_NAME
LEFT JOIN RDB$INDEX_SEGMENTS s2 ON i2.RDB$INDEX_NAME = s2.RDB$INDEX_NAME
WHERE
rc.RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'
--rc.RDB$CONSTRAINT_TYPE = 'UNIQUE' 
--rc.RDB$CONSTRAINT_TYPE <> 'FOREIGN KEY'
ORDER BY s.RDB$FIELD_POSITION
