SELECT ADD_MONTHS(SYSDATE, 2) AS AFTER_2_MONTH FROM dual;
SELECT EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, 2)) AS AFTER_2_MONTH FROM dual;

SELECT ADD_MONTHS(SYSDATE, -1) AS BEFORE_MONTH FROM dual;
SELECT EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1)) AS BEFORE_MONTH FROM dual;