SELECT 
   CASE WHEN EXISTS(#SELECT_QUERY#) 
     THEN 1 
     ELSE 0 
   END 
FROM dual;


SELECT CAST(1 AS NUMBER(1,0)) AS EXST FROM DUAL WHERE EXISTS(#SELECT_QUERY#);



SELECT 
  CAST(CASE WHEN EXISTS(#SELECT_QUERY#) 
     THEN 1 
     ELSE 0 
   END AS NUMBER(1,0)) AS EXST
FROM DUAL;
