  SELECT ACD.COMMENTS AS "COLUMN DEFINITION",ATC.*
    FROM ALL_TAB_COLUMNS ATC
         LEFT JOIN ALL_COL_COMMENTS ACD
            ON     ATC.OWNER = ACD.OWNER
               AND ATC.TABLE_NAME = ACD.TABLE_NAME
               AND ATC.COLUMN_NAME = ACD.COLUMN_NAME
   WHERE ATC.OWNER = :POWNER
