SELECT 'ALTER ' || object_type ||' '|| object_name ||' COMPILE;' AS RECOMPILE_SCRIPT,
       object_type,
       object_name,
       status
FROM   user_objects
WHERE  status = 'INVALID' --AND object_name <> 'GET_PARENT_ID'
ORDER BY  object_type, object_name;


DECLARE
  CURSOR P_CURSOR IS
SELECT * FROM (
SELECT 'ALTER ' || object_type ||' '|| object_name ||' COMPILE; COMMIT;' AS RECOMPILE_SCRIPT
FROM   user_objects WHERE  status = 'INVALID' AND object_name <> 'GET_PARENT_ID'
);
   P_ROW P_CURSOR%ROWTYPE; 
BEGIN 
   OPEN P_CURSOR;
   LOOP
    FETCH  P_CURSOR INTO P_ROW;
    EXIT WHEN P_CURSOR%NOTFOUND;
BEGIN SAVEPOINT SP_A;
BEGIN 
DBMS_OUTPUT.PUT_LINE(P_ROW.RECOMPILE_SCRIPT);
EXECUTE IMMEDIATE P_ROW.RECOMPILE_SCRIPT;
--EXECUTE P_ROW.RECOMPILE_SCRIPT;
-- INSERT, UPDATE, DELETE QUERY
COMMIT;
 EXCEPTION
 WHEN OTHERS THEN
 ROLLBACK WORK TO SP_A;
END;
END;
  END LOOP; 
  CLOSE P_CURSOR;
END;
