SELECT * FROM (SELECT ROWNUM AS R, T1.* FROM (
SELECT 'D' AS CH FROM DUAL
UNION
SELECT 'C' AS CH FROM DUAL
UNION
SELECT 'AB' AS CH FROM DUAL
UNION
SELECT 'B' AS CH FROM DUAL
) T1) 
ORDER BY R;