SELECT 
KCU.CONSTRAINT_NAME AS F_CONSTRAINT_NAME, KCU.TABLE_NAME AS F_TABLE_NAME, KCU.COLUMN_NAME AS F_COLUMN_NAME, 
KCU2.CONSTRAINT_NAME AS R_CONSTRAINT_NAME, KCU2.TABLE_NAME AS R_TABLE_NAME, KCU2.COLUMN_NAME AS R_COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC 
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU ON TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC ON TC.CONSTRAINT_NAME = RC.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU2 ON  RC.UNIQUE_CONSTRAINT_NAME = KCU2.CONSTRAINT_NAME
WHERE TC.CONSTRAINT_TYPE = 'FOREIGN KEY'
